### PR TITLE
Add Inventory Payload service

### PR DESCRIPTION
**Pull request by fdupont-redhat**
The [Inventory Payload](https://github.com/konveyor/virt-payload) service is added to Konveyor for VMs to allow to extract the inventory for Xavier Analytics.
This pull request adds the Deployment, Service and Route for it.

### CODE REVIEW

**Review by fbladilo — APPROVED** [review]

**Comment by fbladilo** [comment]
Waiting on konveyor Quay images before merging

**Comment by mturley** [comment]
@fdupont-redhat is is possible for the operator to also include the URL for this service in its `virtMeta.json` that it provides to the UI?

**Comment by fdupont-redhat** [comment]
@mturley it will be available as `inventoryPayloadApi` in`virtMeta.json`.

**Comment by mturley** [comment]
Perfect, thanks @fdupont-redhat ! Updated https://github.com/konveyor/virt-ui/issues/109

**Comment by fdupont-redhat** [comment]
The konveyor/virt-payload repository is now live and the container image is available in Quay.
@fbladilo would you mind reviewing again and merge if you're fine with it?

**Comment by fbladilo** [comment]
@fdupont-redhat Are we at the point that we can set resource requirements for these components?

**Comment by fdupont-redhat** [comment]
@pemcg, do you know how much resources your container will consume?
It would be ideal to know min and max limits for CPU and memory.

**Review by fbladilo — APPROVED** [review]
LGTM

**Pull request merged**
